### ISSUE TITLE
Incorrect category for json files

### ISSUE THREAD

**Issue by ShenZheng2000** [Mazin-Hnewa/subsets#1]
Hi, thanks for your amazing work.

I just found the JSON files provided by you have only one category 'vehicle' for various vehicles, whereas the BDD100k official files have bus, truck, motorcycle, and bicycle. 

Did you modify the original JSON file when preparing the subsets?

![image](https://user-images.githubusercontent.com/69662345/201501722-df290b61-0104-4eff-82b6-806442bce6f2.png)

**Comment by Mazin-Hnewa** [comment]
Yes,  I modified the original JSON file because we focus on specific categories in our project. Also, we don't consider some categories such as train, rider, motorcycle, and bicycle because there are not enough instants of them in the set of images we used in our work.  Also, there  are not enough instants of truck and bus. So, we merged car, truck, and bus in one category (vehicle). As a result, we have four categories (vehicle, person, traffic light and traffic sign).

**Comment by ShenZheng2000** [comment]
Hi, Mazin! Could you please release the pretrained weight for UNIT or specify the training code you have used? I want to test it on some custom rainy images. Thanks.

**Comment by Mazin-Hnewa** [comment]
This is the code I used to generate rainy images from clear ones:
https://github.com/mingyuliutw/UNIT

**Comment by ShenZheng2000** [comment]
Appreciate your timely reply!

**Comment by ShenZheng2000** [comment]
Hello, Mazin! Your paper mentioned that "we extract a sufficiently large number
of images from the rainy videos of BDD100K data set". However, downloading videos from the bdd100k [link](http://dl.yf.io/bdd100k/video_parts/) is extremely slow. Is there any other link for a quick download?

![image](https://user-images.githubusercontent.com/69662345/212496404-c33ad084-999b-4213-9876-3cdcb390b174.png)

**Comment by Mazin-Hnewa** [comment]
Based on my knowledge, I don't know any alternative link to download the video.
However, you can download our extracted rainy images from the repo.
